# Generated by Django 3.2.3 on 2021-05-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
